sudo: required

servies:
- docker

env:
- VERSION=7.2
- VERSION=7.1
- VERSION=7.0
- VERSION=5.6

jobs:
  include:
    - stage: build
      env:
      - TYPE=fpm
      script:
      - echo "${DOCKER_PASSWORD}" | docker login -u $DOCKER_USERNAME --password-stdin
      - docker build -t dockerizr/php:${VERSION}-${TYPE} {VERSION}/${TYPE}
      - docker push dockerizr/php:${VERSION}-${TYPE}
    - env:
      - TYPE=cli
      script:
      - echo "${DOCKER_PASSWORD}" | docker login -u $DOCKER_USERNAME --password-stdin
      - docker build -t dockerizr/php:${VERSION}-${TYPE} {VERSION}/${TYPE}
      - docker push dockerizr/php:${VERSION}-${TYPE}